// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Recommends a surprise meal to the user based on their dietary preferences and past choices.
 *
 * - getSurpriseMealRecommendation - A function that gets a surprise meal recommendation.
 * - SurpriseMealRecommendationInput - The input type for the getSurpriseMealRecommendation function.
 * - SurpriseMealRecommendationOutput - The return type for the getSurpriseMealRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SurpriseMealRecommendationInputSchema = z.object({
  dietaryPreferences: z
    .string()
    .describe('The dietary preferences of the user, e.g. vegetarian, vegan, gluten-free.'),
  pastChoices: z
    .string()
    .describe('The past meal choices of the user, e.g. pasta, salad, chicken.'),
});
export type SurpriseMealRecommendationInput =
  z.infer<typeof SurpriseMealRecommendationInputSchema>;

const SurpriseMealRecommendationOutputSchema = z.object({
  mealRecommendation: z
    .string()
    .describe('A surprise meal recommendation based on the user preferences.'),
});
export type SurpriseMealRecommendationOutput =
  z.infer<typeof SurpriseMealRecommendationOutputSchema>;

export async function getSurpriseMealRecommendation(
  input: SurpriseMealRecommendationInput
): Promise<SurpriseMealRecommendationOutput> {
  return surpriseMealRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'surpriseMealRecommendationPrompt',
  input: {schema: SurpriseMealRecommendationInputSchema},
  output: {schema: SurpriseMealRecommendationOutputSchema},
  prompt: `You are a meal recommendation expert. Based on the user's dietary preferences and past choices, you will recommend a surprise meal.

Dietary Preferences: {{{dietaryPreferences}}}
Past Choices: {{{pastChoices}}}

Recommend a surprise meal:`,
});

const surpriseMealRecommendationFlow = ai.defineFlow(
  {
    name: 'surpriseMealRecommendationFlow',
    inputSchema: SurpriseMealRecommendationInputSchema,
    outputSchema: SurpriseMealRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
