
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a witty confirmation message for the free lunch giveaway.
 *
 * - getWittyConfirmation - A function that generates a witty confirmation.
 * - WittyConfirmationInput - The input type for the getWittyConfirmation function.
 * - WittyConfirmationOutput - The return type for the getWittyConfirmation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const WittyConfirmationInputSchema = z.object({
  email: z.string().describe('The email address of the user who signed up.'),
});
export type WittyConfirmationInput = z.infer<typeof WittyConfirmationInputSchema>;

const WittyConfirmationOutputSchema = z.object({
  confirmationMessage: z
    .string()
    .describe('A witty, sarcastic, and funny confirmation message for the user.'),
});
export type WittyConfirmationOutput = z.infer<typeof WittyConfirmationOutputSchema>;

export async function getWittyConfirmation(
  input: WittyConfirmationInput
): Promise<WittyConfirmationOutput> {
  return wittyConfirmationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'wittyConfirmationPrompt',
  input: {schema: WittyConfirmationInputSchema},
  output: {schema: WittyConfirmationOutputSchema},
  prompt: `You are the playfully savage voice of a corporate lunch delivery service called "11 to 12".
Your target audience is burnt-out 9-to-5 office workers in Nigeria.
A user has just submitted their email for a chance to win a free lunch.
Generate a short, funny, and slightly savage confirmation message for them.
Acknowledge that they've been entered but don't promise they've won.
Make it sound like a colleague who understands the Lagos office grind (traffic, stress, etc.).

User's email: {{{email}}}
`,
});

const wittyConfirmationFlow = ai.defineFlow(
  {
    name: 'wittyConfirmationFlow',
    inputSchema: WittyConfirmationInputSchema,
    outputSchema: WittyConfirmationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
